#! /usr/bin/env python3

import asyncio
import argparse
import functools
import os
import pathlib
import signal
import sys


PUBLIC_PORT = 8000
PRIVATE_PORT = 9000


class ProcessError(Exception):

    def __init__(self, rv):
        self._rv = rv

    def __str__(self):
        return f'failed with code: {self._rv}'


async def main(args=None):
    if args is None:
        args = sys.argv

    stop_event = setup()

    args = parse_args(args)

    try:
        if not args.debug:
            await run_release(
                public_listen=args.public_listen,
                token=args.token,
            )
        else:
            await run_debug(
                public_listen=args.public_listen,
                private_listen=args.private_listen,
                stop_event=stop_event,
                token=args.token,
            )
    except Exception as e:
        print(e)
        return 1

    return 0


def close(stop_event):
    stop_event.set()


def setup():
    loop = asyncio.get_running_loop()
    stop_event = asyncio.Event()
    fn = functools.partial(close, stop_event)
    loop.add_signal_handler(signal.SIGINT, fn)
    loop.add_signal_handler(signal.SIGTERM, fn)
    return stop_event


def parse_args(args):
    parser = argparse.ArgumentParser('dvd')
    parser.add_argument('-d', '--debug', action='store_true')
    parser.add_argument('--public-listen', type=int, default=PUBLIC_PORT)
    parser.add_argument('--private-listen', type=int, default=PRIVATE_PORT)
    parser.add_argument('--token', type=str)
    args = parser.parse_args(args[1:])
    return args


async def run_release(public_listen: int, token: str):
    await run_or_die(['make', '-j'])
    cmd = [
        'python3', '-m', 'engine',
            '-u', '../unpack/build/unpack',
            '-s', '../viewer/dist',
            '-l', str(public_listen),
    ]
    if token:
        cmd.extend(['-t', token])
    await run_or_die(cmd, cwd=pathlib.Path('./engine'))


async def run_debug(
    public_listen: int,
    private_listen: int,
    stop_event: asyncio.Event,
    token: str,
):
    await run_or_die(['make', '-j', 'debug'])

    cmd = [
        'python3', '-m', 'wcpan.watchdog',
            '--',
            'python3', '-m', 'engine',
                '-u', '../unpack/build/unpack',
                '-l', str(private_listen),
    ]
    if token:
        cmd.extend(['-t', token])
    backend = run_or_die(
        cmd,
        cwd=pathlib.Path('./engine'),
    )

    frontend = run_or_die(
        [
            'yarn', 'start',
                '--host=0.0.0.0',
                f'--port={public_listen}',
        ],
        cwd=pathlib.Path('./viewer'),
        env=clone_env({
            'BACKEND_PORT': str(private_listen),
        }),
    )
    frontend_task = asyncio.create_task(frontend)
    fn = functools.partial(stop_backend, stop_event=stop_event)
    frontend_task.add_done_callback(fn)

    await asyncio.wait([
        asyncio.create_task(backend),
        frontend_task,
    ])


async def run_or_die(cmd, cwd=None, env=None):
    p = await spawn(cmd, cwd=cwd, env=env)
    await ok_or_die(p)


async def spawn(cmd, cwd=None, env=None):
    return await asyncio.create_subprocess_exec(*cmd, cwd=cwd, env=env)


async def ok_or_die(p):
    rv = await p.wait()
    if rv > 0:
        raise ProcessError(rv)


def stop_backend(frontend_task, *, stop_event):
    if frontend_task.exception():
        stop_event.set()


def clone_env(override=None):
    env = os.environ.copy()
    if override:
        env.update(override)
    return env


if __name__ == '__main__':
    sys.exit(asyncio.run(main()))
