root: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:svelte/recommended
  - prettier
plugins:
  - "@typescript-eslint"
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  ecmaVersion: 2020
  extraFileExtensions:
    - .svelte
overrides:
  - files:
      - "*.svelte"
    parser: svelte-eslint-parser
    parserOptions:
      parser: "@typescript-eslint/parser"
env:
  browser: true
  es2017: true
  node: true
rules:
  # See sveltejs/eslint-plugin-svelte#348
  "@typescript-eslint/no-unused-vars":
    - error
    - varsIgnorePattern: "^\\$\\$(Props|Events|Slots)$"
