name: unpack

on:
  push:
    paths:
      - '.github/workflows/unpack.yaml'
      - 'unpack/**'
  pull_request:
    paths:
      - '.github/workflows/unpack.yaml'
      - 'unpack/**'

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build-type:
          - debug
          - release
    steps:
      - uses: actions/checkout@v4
      - name: apt update
        run: sudo apt-get update
      - name: Install Dependencies
        run: sudo apt-get install -y --no-install-recommends build-essential cmake libarchive-dev libboost-locale-dev libcurl4-openssl-dev libssl-dev
      - name: Build
        working-directory: unpack
        run: make ${{ matrix.build-type }}
  MacOSX:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        build-type:
          - debug
          - release
    steps:
      - uses: actions/checkout@v4
      - name: Update Homebrew
        run: brew update
      - name: Install Dependencies
        run: brew install libarchive boost curl
      - name: Build
        working-directory: unpack
        env:
          CMAKE_PREFIX_PATH: /opt/homebrew/opt/libarchive
        run: make ${{ matrix.build-type }}
